
target 'test_proj' do
  pod 'GVRSDK'  

  target 'test_proj-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test_projTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
